[package]
name = "gadget-eigenlayer-testing-utils"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
gadget-std = { workspace = true }
gadget-anvil-testing-utils = { workspace = true }
gadget-core-testing-utils = { workspace = true }
gadget-config = { workspace = true, features = ["eigenlayer"] }
gadget-logging = { workspace = true }
gadget-utils = { workspace = true, features = ["eigenlayer", "evm"] }
gadget-macros = { workspace = true, features = ["evm"] }
gadget-runners = { workspace = true, features = ["eigenlayer"] }
gadget-event-listeners = { workspace = true, features = ["evm"] }
tempfile = { workspace = true }
async-trait = { workspace = true }
alloy-primitives = { workspace = true }
alloy-provider = { workspace = true }
alloy-rpc-types = { workspace = true }
alloy-rpc-types-eth = { workspace = true }
alloy-transport = { workspace = true }
eigensdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, features = ["alloc"] }
testcontainers = { workspace = true }
tokio = { workspace = true, features = ["full"] }
url = { workspace = true }