[package]
name = "gadget-blueprint-proc-macro-playground"
version = "0.1.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[package.metadata.blueprint]
manager = { Evm = "" }

[[package.metadata.gadget.Native.sources]]
owner = "tangle-network"
repo = "incredible-squaring"
tag = "0.1.0"
binaries = [
    { arch = "Amd64", os = "Linux", name = "amd64-linux-incredible-squaring-gadget" },
    { arch = "Arm64", os = "Linux", name = "arm64-linux-incredible-squaring-gadget" },
]

[dependencies]
async-trait = { workspace = true }
tracing = { workspace = true }
gadget-sdk = { workspace = true, features = ["default"] }

[dev-dependencies]
reqwest = { workspace = true }
serde_json = { workspace = true, features = ["alloc"] }
tokio = { workspace = true }
blueprint-examples = { workspace = true }

[build-dependencies]
blueprint-metadata = { workspace = true }
