[package]
name = "blueprint-metadata"
version = "0.2.1"
description = "A build dependency for generating metadata for Blueprint at compile time."
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
gadget-blueprint-proc-macro-core.workspace = true
gadget-std = { workspace = true, features = ["std"] }

typed-builder.workspace = true
serde.workspace = true
serde_json.workspace = true
rustdoc-types.workspace = true
cargo_metadata.workspace = true
fs2.workspace = true
