[package]
name = "gadget-core-testing-utils"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
cargo_toml = { workspace = true }
gadget-runners = { workspace = true, features = ["std"] }
gadget-config = { workspace = true, features = ["std"] }
gadget-logging = { workspace = true, features = ["std"] }
gadget-clients = { workspace = true, features = ["std"] }
gadget-keystore = { workspace = true, features = ["std"] }
gadget-event-listeners = { workspace = true, features = ["std"] }
thiserror = { workspace = true }
url = { workspace = true }
tokio = { workspace = true, features = ["full"] }
futures = { workspace = true }
async-trait = { workspace = true }
tempfile = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
