[package]
name = "gadget-config"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# Core dependencies (always included)
clap = { workspace = true, features = ["derive", "env"] }
gadget-std = { workspace = true }
lock_api = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, optional = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true, features = ["serde"] }

# Optional dependencies (feature-gated)
libp2p = { workspace = true, optional = true }
alloy-primitives = { workspace = true, optional = true }

# Keystore
gadget-keystore = { workspace = true, optional = true }

[features]
default = ["std", "tangle"]
std = ["gadget-std/std", "serde_json"]

# Core feature groups
keystore = ["gadget-keystore/default"]
networking = ["dep:libp2p"]

# Protocol-specific features
tangle = []
eigenlayer = ["dep:alloy-primitives"]
symbiotic = ["dep:alloy-primitives"]

# Testing features
test-utils = ["std"]
