[package]
name = "gadget-config"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# Core dependencies (always included)
clap = { workspace = true, features = ["derive", "env"] }
gadget-std = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["alloc"], optional = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true, features = ["serde"] }

# Optional dependencies (feature-gated)
libp2p = { workspace = true, optional = true }
gadget-networking = { workspace = true, optional = true }
gadget-keystore = { workspace = true, optional = true, features = ["sp-core", "std"] }
alloy-primitives = { workspace = true, features = ["serde"], optional = true }

[dev-dependencies]
alloy-primitives = { workspace = true, features = ["serde"] }
gadget-config = { path = ".", features = ["std", "eigenlayer", "symbiotic", "tangle", "networking"] }
gadget-std = { workspace = true, features = ["std"] }
libp2p = { workspace = true }


[features]
default = ["std"]
std = [
	"alloy-primitives/std",
	"clap/std",
	"gadget-std/std",
	"serde/std",
	"serde_json/std",
]
eigenlayer = ["dep:alloy-primitives"]
symbiotic = ["dep:alloy-primitives"]
tangle = []
networking = ["libp2p", "gadget-networking", "keystore", "gadget-keystore"]

# Core feature groups
keystore = []

# Testing features
test-utils = ["std"]
