[package]
name = "blueprint-sdk"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
default = ["std", "build", "networking"]
std = [
	"gadget-client-tangle?/std",
	"gadget-networking?/std",
	"gadget-keystore/std",
	"gadget-client-networking?/std",
	"sp-core/std",
	"tokio/default",
]

macros = [

]

build = ["blueprint-metadata", "blueprint-build-utils"]

tangle = [
	"tangle-blueprint-sdk",
	"gadget-testing-utils?/tangle"
]

eigenlayer = [
	# TODO: Add eigenlayer SDK
]

testing = [
	"gadget-client-tangle",
	"gadget-tangle-testing-utils",
	"gadget-testing-utils",
	"tempfile"
]

networking = [
	"gadget-networking",
	"gadget-client-networking",
	"gadget-contexts/networking",
	"gadget-clients/networking",
	"gadget-keystore/std",
	"gadget-config/networking",
]

round-based-compat = ["gadget-networking/round-based-compat"]

[dependencies]
# SDKs
tangle-blueprint-sdk = { workspace = true, optional = true }

# Required dependencies
gadget-keystore = { workspace = true }
gadget-config = { workspace = true }

# Required Features for macro resolution
sp-core = { workspace = true, default-features = false }
tokio = { workspace = true, default-features = false }

# Networking-related dependencies
gadget-networking = { workspace = true, optional = true }
gadget-client-networking = { workspace = true, optional = true }
gadget-contexts = { workspace = true, optional = true }
gadget-clients = { workspace = true, optional = true }


# Optional dependencies for testing
gadget-client-tangle = { workspace = true, optional = true }
gadget-tangle-testing-utils = { workspace = true, optional = true }
gadget-testing-utils = { workspace = true, optional = true }
tempfile = { version = "3.13.0", optional = true }

# Optional dependencies for build
blueprint-metadata = { workspace = true, optional = true }
blueprint-build-utils = { workspace = true, optional = true }