[package]
name = "gadget-crypto-sp-core"
version = "0.1.0"
edition = "2021"

[dependencies]
gadget-std = { workspace = true }
gadget-crypto-core = { workspace = true, features = ["tangle"] }
sp-core = { workspace = true, features = ["serde"] }
hex = { workspace = true, features = ["alloc"] }
paste = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true, features = ["alloc"] }
thiserror = { workspace = true }

# TODO: remove whenever possible: https://github.com/paritytech/polkadot-sdk/pull/1983#discussion_r1368625867
sp-runtime-interface = { workspace = true, features = ["disable_target_static_assertions"] }

[dev-dependencies]
gadget-crypto-sp-core = { path = ".", features = ["std", "bls"] }
serde_json = { workspace = true, features = ["alloc"] }

[features]
default = ["std"]
std = [
	"gadget-crypto-core/std",
	"gadget-std/std",
	"serde/std",
	"serde_bytes/std",
	"sp-core/std",
]
bls = ["sp-core/bls-experimental"]