[package]
name = "gadget-utils-tangle"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
async-trait = { workspace = true, default-features = false }
gadget-std = { workspace = true, default-features = false }
gadget-logging = { workspace = true, default-features = false }
subxt = { workspace = true, default-features = false }
tracing = { workspace = true, default-features = false, features = ["attributes"] }

[features]
default = ["std"]
std = [
    "gadget-std/std",
    "gadget-logging/std",
    "subxt/native",
]
no_std = ["subxt/web"]