[package]
name = "gadget-contexts"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
gadget-std = { workspace = true }
gadget-clients = { workspace = true }
gadget-keystore = { workspace = true, optional = true }

subxt = { workspace = true, optional = true }

[features]
default = ["std", "keystore"]
std = [
    "gadget-std/std",
    "gadget-keystore?/std",
]

evm = ["gadget-clients/evm"]
eigenlayer = ["gadget-clients/eigenlayer"]
networking = ["gadget-clients/networking"]
keystore = ["gadget-keystore"]
tangle = ["dep:subxt", "gadget-clients/tangle"]