[package]
name = "gadget-event-listeners-periodic"
version = "0.1.0"
edition = "2021"

[dependencies]
gadget-std = { workspace = true }
gadget-event-listeners-core = { workspace = true }
gadget-logging = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[features]
default = ["std"]
std = [
    "gadget-std/std",
    "gadget-event-listeners-core/std",
    "gadget-logging/std",
    "tokio/full",
]