[package]
name = "gadget-networking"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# Internal deps
gadget-logging = { workspace = true }
gadget-std = { workspace = true }

# Core dependencies
auto_impl = { workspace = true }
dashmap = { workspace = true }
libp2p = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
futures = { workspace = true }
tracing = { workspace = true }
bincode = { workspace = true }
async-trait = { workspace = true }
lru-mem = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, features = ["alloc"] }
hex = { workspace = true }
itertools = { workspace = true, features = ["use_alloc"] }
parking_lot = { workspace = true }
thiserror = { workspace = true }

# Crypto dependencies
gadget-crypto = { workspace = true, features = ["k256", "hashing"] }
k256 = { workspace = true }

# Round-based protocol support
round-based = { workspace = true, optional = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies.libp2p]
workspace = true
features = [
	"tokio",
	"gossipsub",
	"mdns",
	"noise",
	"macros",
	"yamux",
	"tcp",
	"quic",
	"request-response",
	"cbor",
	"identify",
	"kad",
	"dcutr",
	"relay",
	"ping",
	"dns",
	"autonat",
]

[dev-dependencies]
tracing-subscriber = { workspace = true }
lazy_static = { workspace = true }

[features]
default = ["std"]
std = [
	"gadget-crypto/std",
	"gadget-logging/std",
	"gadget-std/std",
	"gadget-std/tokio",
	"k256/std",
	"tokio/full",
	"serde/std",
	"serde_json/std",
	"round-based?/std",
]

round-based-compat = ["round-based"]

# Only one of these features should be enabled at a time.
# If none are enabled, k256 ECDSA will be used by default.
sp-core-ecdsa = ["gadget-crypto/sp-core"]
sp-core-sr25519 = ["gadget-crypto/sp-core"]
sp-core-ed25519 = ["gadget-crypto/sp-core"]

[lints]
workspace = true
