[profile.default]
src = "contracts/src"
test = "contracts/test"
out = "contracts/out"
script = "contracts/script"
cache_path = "contracts/cache"
broadcast = "contracts/broadcast"
libs = ["dependencies"]
remappings = [
    "@eigenlayer/=dependencies/eigenlayer-middleware-0.4.3/lib/eigenlayer-contracts/src/",
    "@eigenlayer-middleware/=dependencies/eigenlayer-middleware-0.4.3/",
    "forge-std-1.9.5/=dependencies/forge-std-1.9.5/",
    "incredible-squaring/=contracts/src/",
]

[soldeer]
recursive_deps = true
remappings_location = "txt"
remappings_version = false

[dependencies]
eigenlayer-middleware = { version = "0.4.3", git = "https://github.com/Layr-Labs/eigenlayer-middleware" }
forge-std = "1.9.5"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options