[package]
name = "gadget-context-derive"
version = "0.3.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Procedural macros for deriving Context Extension traits from `gadget-sdk`"

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["full"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }

[dev-dependencies]
async-trait.workspace = true
trybuild = { workspace = true }
# EVM Stuff
alloy-network = { workspace = true }
alloy-provider = { workspace = true }
alloy-transport = { workspace = true }
gadget-config.workspace = true
gadget-networking.workspace = true
gadget-contexts.workspace = true
gadget-context-derive = { workspace = true, features = ["std", "tangle", "evm"] }
gadget-macros = { workspace = true, features = ["std", "evm", "tangle"] }
gadget-stores = { workspace = true, features = ["std"] }
round-based = { workspace = true, features = ["derive"] }
serde = { workspace = true }
subxt-core.workspace = true

[features]
default = ["std"]
std = []

tangle = []
evm = []
