[package]
name = "gadget-clients"
version = "0.1.0"
edition = "2021"

[dependencies]
gadget-client-eigenlayer = { workspace = true, optional = true }
gadget-client-evm = { workspace = true, optional = true }
gadget-client-tangle = { workspace = true, optional = true }
gadget-client-networking = { workspace = true, optional = true }
thiserror = { workspace = true }

[features]
default = ["std", "eigenlayer", "evm", "networking", "tangle"]
std = [
    "gadget-client-eigenlayer?/std",
    "gadget-client-evm?/std",
    "gadget-client-networking?/std",
    "gadget-client-tangle?/std",
]
web = ["gadget-client-tangle?/web"]

eigenlayer = ["gadget-client-eigenlayer"]
evm = ["gadget-client-evm"]
networking = ["gadget-client-networking"]
tangle = ["gadget-client-tangle"]