[package]
name = "gadget-event-listeners-tangle"
version = "0.1.0"
edition = "2021"

[dependencies]
gadget-blueprint-serde = { workspace = true }
gadget-clients = { workspace = true, features = ["tangle"] }
gadget-contexts = { workspace = true, features = ["keystore", "tangle"] }
gadget-crypto = { workspace = true, features = ["tangle-pair-signer"] }
gadget-event-listeners-core = { workspace = true }
gadget-logging = { workspace = true }
gadget-std = { workspace = true }
gadget-utils-tangle = { workspace = true }

async-trait = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sp-core = { workspace = true }
tangle-subxt = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[features]
default = ["std"]
std = [
	"gadget-blueprint-serde/std",
	"gadget-clients/std",
	"gadget-contexts/std",
	"gadget-crypto/std",
	"gadget-event-listeners-core/std",
	"gadget-logging/std",
	"gadget-std/std",
	"gadget-utils-tangle/std",
	"serde/std",
	"sp-core/std",
	"tangle-subxt/std",
	"tokio/full",
]
web = [
	"gadget-utils-tangle/web",
	"tangle-subxt/web",
]