[profile.ci]
failure-output = "immediate-final"
fail-fast = false
slow-timeout = { period = "60s", terminate-after = 4 }

[profile.serial]
test-threads=1
failure-output = "immediate-final"
fail-fast = false
slow-timeout = { period = "60s", terminate-after = 4 }