[package]
name = "gadget-store-local-database"
version = "0.1.0"
edition = "2021"

[dependencies]
gadget-std = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["alloc"] }

[features]
default = ["std"]
std = [
    "gadget-std/std",
    "serde/std",
    "serde_json/std",
]

[dev-dependencies]
tempfile = "3.8"