[package]
name = "gadget-std"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
async-trait = { workspace = true, optional = true }
rand = { workspace = true, features = ["std_rng"] }
rayon = { workspace = true, optional = true }
num-traits.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync", "time"], optional = true }

[dev-dependencies]
rand = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["sync", "time", "macros", "rt"] }

[features]
default = ["std"]
std = ["thiserror/std", "getrandom"]
tokio = ["dep:async-trait", "dep:tokio"]
parallel = ["rayon", "std"]
print-trace = ["std"]
getrandom = ["rand/std"]
