[package]
name = "incredible-squaring-blueprint"
version = "0.1.1"
description = "A Simple Blueprint to demo how blueprints work on Tangle Network"
edition = "2021"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[dependencies]
# Gadget dependencies
blueprint-sdk = { workspace = true, features = ["std", "macros", "tangle"] }

[dev-dependencies]
blueprint-sdk = { workspace = true, features = ["std", "macros", "tangle", "testing"] }
color-eyre = { workspace = true, features = ["capture-spantrace", "track-caller"] }
tokio = { workspace = true, features = ["full"] }

[build-dependencies]
blueprint-metadata.workspace = true

[package.metadata.blueprint]
manager = { Evm = "IncredibleSquaringBlueprint" }
master_revision = "Latest"
