[package]
name = "incredible-squaring-blueprint"
version = "0.1.1"
description = "A Simple Blueprint to demo how blueprints work on Tangle Network"
edition = "2021"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[dependencies]
# Gadget dependencies
blueprint-sdk = { workspace = true, features = ["std", "macros", "tangle"] }
tracing = { workspace = true }
tracing-core = { workspace = true }

[dev-dependencies]
blueprint-sdk = { workspace = true, features = ["std", "macros", "tangle", "testing"] }

# TODO: Move into testing crate
alloy-signer-local = { workspace = true }
color-eyre = { workspace = true, features = ["capture-spantrace", "track-caller"] }
cargo-tangle = { workspace = true, features = ["tangle"] }
futures-util = { workspace = true }

tokio = { workspace = true, features = ["full"] }
tempfile = { workspace = true }
gadget-client-tangle = { workspace = true }
gadget-testing-utils = { workspace = true, features = ["tangle"] }
async-trait = { workspace = true }
url = { workspace = true }

[build-dependencies]
blueprint-metadata.workspace = true

[features]

[package.metadata.blueprint]
manager = { Evm = "IncredibleSquaringBlueprint" }
master_revision = "Latest"
