[package]
name = "gadget-blueprint-proc-macro"
version = "0.5.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Procedural macros for writing Tangle blueprints"

[lib]
proc-macro = true

[dependencies]
gadget-std.workspace = true
gadget-blueprint-proc-macro-core.workspace = true

syn = { workspace = true, features = ["full"] }
quote = { workspace = true }
itertools = { workspace = true }
proc-macro2 = { workspace = true }
serde_json = { workspace = true, features = ["alloc"] }
indexmap = { workspace = true }

[dev-dependencies]
trybuild = { workspace = true }
gadget-event-listeners = { workspace = true, features = ["testing"] }
gadget-macros = { workspace = true }

[features]
default = ["std"]
std = ["gadget-blueprint-proc-macro-core/std", "gadget-std/std", "indexmap/std"]
