[package]
name = "tangle-blueprint-sdk"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
default = ["std"]

std = [
    "gadget-event-listeners/std",
    "gadget-config/std",
    "gadget-logging/std",
    "gadget-store-local-database/std",
    "gadget-macros/std",
    "gadget-runners/std",
    "gadget-crypto/std",
    "gadget-crypto-tangle-pair-signer/std",
]

[dependencies]
# Tangle dependencies
gadget-event-listeners = { workspace = true, features = ["tangle"] }
gadget-macros = { workspace = true, features = ["tangle", "networking"] }
gadget-crypto = { workspace = true }
gadget-crypto-tangle-pair-signer = { workspace = true }
gadget-config = { workspace = true }
gadget-logging = { workspace = true }
gadget-runners = { workspace = true, features = ["tangle"] }
gadget-store-local-database = { workspace = true }


[lints]
workspace = true